server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    discovery:
      locator:
        enabled: true # Enables dynamic routing
    gateway:
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
